### PR TITLE
Unit test

### LINKED ISSUE #45: Implement unit test
Implement & document the unit testing suite for the entire site.

### PR DESCRIPTION
**Pull request by JR-prog**
Implemented unit tests for most pages / functionalities. 
To run the unit tests: `php artisan test` 
On this branch, there should be 2 failures (browsing & cart). Cart has not yet been merged and browsing is meant as an example of what a failed unit test looks like.
Unit tests for managing profiles, cart and checkout will be implemented with their respective features.

Closes #45

### CODE REVIEW

**Comment by MariaR001** [comment]
Tested it out and it works.

**Comment by hilary-ostof** [comment]
I tested it out and it worked as expected on my side

**Review by hilary-ostof — APPROVED** [review]

**Review by AryanSh1380 — APPROVED** [review]
testing is also successful on my end and the unit tests behave as expected.

**Review by chloehylaw — APPROVED** [review]
Good!

**Pull request merged**
