### PR TITLE
Checkout

### LINKED ISSUE #23: Implement checkout page layout
Create HTML template for the checkout page.
*This does not include database functionality*

### LINKED ISSUE #24: Implement checkout page functionality
Using the template in:
- [x] #23 

Implement the functionality of the checkout page. This includes database functionality (check database schema for how to enter order & sales info) to save an order and *optionally* cart functionalities like increment/decrement (if you want to make your life harder).

### LINKED ISSUE #25: User checkout
As a customer, I want to be able to checkout (buy) all the items in my cart, and get all the information associated with the order. This information includes delivery address (which I predefined in my profile), shipping information, items, total cost, order ID (confirmation).
- [x] #22 
- [x] #23 
- [x] #24

### PR DESCRIPTION
**Pull request by JR-prog**
Make sure to run `php artisan migrate`

With these changes, if the user is logged in, they can proceed to checkout and checkout, which creates an order entry in the database, as well as a sale entry for each item that was in the cart. It also removes all items from the cart.
*Note that there is no payment method yet, and checkout is free! (This is because payment methods are captured in issue #49*

There is an issue where the page has an error if the user is not logged in, but this will be solved with the following issue: #61 

Closes #23 
Closes #24 
Closes #25

### CODE REVIEW

**Comment by chloehylaw** [comment]
Works for me! One thing to note is that the footer is not at the bottom and makes the whole screen ugly...
In the cart screen, I saw your cart.css and you handled it with .background-cart i think? Maybe do something similar for the checkout screen!
image

**Review by chloehylaw — APPROVED** [review]
It works for me!
Maybe edit your checkout page so the footer is at the bottom? It looks good in your cart page since I think you added the .background-cart in your cart.css
image

**Review by Ariiiane — CHANGES_REQUESTED** [review]
Add a minimum height to the page and it should fixed the footer (same as the cart page)

**Review by Ariiiane — APPROVED** [review]
works now

**Review by AryanSh1380 — APPROVED** [review]
Checkout tests successful on my end, was able to run the migration and can see that oders are added to db. Approving PR for merge

**Review by MariaR001 — APPROVED** [review]
Works on my end! Approved for merge

**Comment by MariaR001** [comment]
Retested it after resolved conflicts and it works.

**Pull request merged**
